# Don't change this, this allows the config to update #
Version: '1.4.1'

# Main title #
KitsTitle: 'Kits'

# Preview title #
KitsPreviewTitle: 'Kit {name} - Preview'

# Kits edit items title #
KitsEditItems: 'Edit {name} - Items'

# Kits main edit title #
EditingAdminUI: 'Edit {name}'

### {cooldown} to get kit cooldown, {name} to get the kit name ###
## Kit lore layout ##

UILayoutBefore:
- '&f--------------------'
- '&5Cooldown: {cooldown}'
- '&aLeft click to choose'
- '&aRight click to preview'

UILayoutAfter:
- '&f--------------------'
- '&5Cooldown: {cooldown}'
- '&aRight click to preview'

UILayoutAdmin:
- '&f--------------------'
- '&aMiddle click to edit'

### 20 = 1 Second ###
## Updates the /kits ##

RefreshRate: 20

## Check if there is a update ##

UpdateChecker: true
