# Don't change this, this allows the config to update #
Version: '1.5'

# Main title #
KitsTitle: 'Kits'

# Preview title #
KitsPreviewTitle: 'Kit {name} - Preview'

# Kits edit items title #
KitsEditItems: 'Edit {name} - Items'

# Kits main edit title #
EditingAdminUI: 'Edit {name}'

# Starting Kit #
StartingKit: 'Starter'

### {cooldown} to get kit cooldown, {name} to get the kit name ###
## Kit lore layout ##

UILayoutBefore:
- '&f--------------------'
- '&5Cooldown: {cooldown}'
- '&aLeft click to choose'
- '&aRight click to preview'

UILayoutAfter:
- '&f--------------------'
- '&5Cooldown: {cooldown}'
- '&aRight click to preview'

# Buyable Kits needs to be enabled to see this #
UIMoneyLayout:
- '&f--------------------'
- '&6Cost: &c{cost}'

UILayoutAdmin:
- '&f--------------------'
- '&aMiddle click to edit'

### 20 = 1 Second ###
## Updates the /kits ##

RefreshRate: 20

### Buyable Kits ###

# Enable this for buyable kits #
BuyableKits: false

# Enable this if you want to use vault (Built in money won't be useable) #
Vault: false

# Get money from killed mobs (Optional) #
MoneyFromMobs: false

# Money Layout #
MoneyLayout: '${money}'

# Default Money (Vault need to be disabled) #
StartingMoney: 10

## Money messages (Buyable Kits need to be enabled) #
MoneyTaken: '&e{cost} &ahas been taken from your account.'
MoneyAdded: '&e{cost} &ahas been added to your account.'

## Check if there is a update ##

UpdateChecker: true
